# Generated by Django 4.2.9 on 2024-03-13 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Blogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("stock_name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "stock_symbol",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "stock_exchange",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                ("stock_scrip_code", models.IntegerField(blank=True, null=True)),
                (
                    "stock_industry",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("market_cap", models.FloatField(blank=True, null=True)),
                ("no_of_shares", models.BigIntegerField(blank=True, null=True)),
                ("live_price", models.FloatField(blank=True, null=True)),
                ("upside_left", models.FloatField(blank=True, null=True)),
                ("expected_returns", models.FloatField(blank=True, null=True)),
                ("time_left", models.IntegerField(blank=True, null=True)),
                (
                    "risk",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("tag1", models.CharField(default="Active", max_length=50)),
                ("tag2", models.CharField(blank=True, max_length=50, null=True)),
                ("exit_price", models.FloatField(blank=True, null=True)),
                ("exit_date", models.DateField(blank=True, null=True)),
                ("free_stock", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="StockTarget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("entry_price", models.FloatField(blank=True, null=True)),
                ("target_price", models.FloatField(blank=True, null=True)),
                ("target_date", models.DateField(blank=True, null=True)),
                (
                    "gain_loss",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "target_action",
                    models.CharField(
                        choices=[("BUY", "BUY"), ("HOLD", "HOLD"), ("SELL", "SELL")],
                        default="BUY",
                        max_length=4,
                    ),
                ),
                (
                    "target_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Active", "Active"),
                            ("Active - Target Met", "Active - Target Met"),
                            ("Inactive - Target Met", "Inactive - Target Met"),
                            (
                                "Inactive - Partial Profit Booked",
                                "Inactive - Partial Profit Booked",
                            ),
                            ("Inactive - Loss Booked", "Inactive - Loss Booked"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kmkadmin.stock"
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="StockReportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_id", models.UUIDField()),
                ("action", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_file", models.FileField(upload_to="stock_reports/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kmkadmin.stock"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stocklog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock", models.UUIDField()),
                ("main_data", models.CharField(max_length=30)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("Stock Added", "Stock Added"),
                            ("Stock Deleted", "Stock Deleted"),
                            ("Stock Edited", "Stock Edited"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
